### ISSUE TITLE
fetch_data error

### ISSUE THREAD

**Issue by zpencerguy** [Squarespace/datasheets#11]
Receiving KeyError message of 'errorValue' when fetching data from a worksheet tab and can't figure out what is causing this.
`---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-63-eb07c13a5a09> in <module>()
      1 worksheet = workbook.fetch_tab(sheets[0])
----> 2 df = worksheet.fetch_data()
      3 df.head()

~\AppData\Local\Continuum\anaconda3\lib\site-packages\datasheets\tab.py in fetch_data(self, headers, fmt)
    444         raw_data = self.sheets_svc.get(spreadsheetId=self.workbook.file_id, ranges=self.tabname,
    445                                        includeGridData=True, fields=fields).execute()
--> 446         processed_rows = self._process_rows(raw_data)
    447 
    448         # filter out empty rows

~\AppData\Local\Continuum\anaconda3\lib\site-packages\datasheets\tab.py in _process_rows(raw_data)
     89                     cell_format = base_fmt
     90 
---> 91                 formatting_fn = helpers._TYPE_CONVERSIONS[cell_format]
     92                 if cell_value:
     93                     try:

KeyError: 'errorValue'`

**Comment by zcmarine** [comment]
[note: I'm on mobile, hence the lousy formatting]

Hey Spencer,

It looks like one of the cells in your tab has an error I'm a cell and datasheets won't import the data as a result. The specific spot in the API docs that mention that is here: https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets#ErrorValue

For your specific use case, if you fix any errors in cells in that tab you should be able to run fetch_data() without issues.

As for how datasheets could be improved  for situations like this, there are a few ways this could be handled:
1. We convert the error into a string and continue processing. This has the advantage that this issue won't occur, but it has a huge disadvantage of giving unexpected results, e.g. a numerical column now has an unexpected string in it. I'm not a fan of this since we're introducing non-obvious behavior.
2. We try to guess at what the default value for that column should be. I'm opposed to this for the same reason as the above.
3. We catch these errors and give the user a more helpful error message, e.g. "Unable to fetch data due to error in cell B17. Please fix this and other errors and fetch again." This feels like the most reasonable approach as it is clear what corrective action is needed and it is really only the end user that has the power to adequately remedy the situation.
4. We do nothing for the moment. This isn't ideal but I'm backpacking in Africa for the next 2 months so unless someone else can do the above it may need to stay this way temporarily.

So options 3 or 4 make the most sense to me. If you or someone else would want to take a shot at addressing this issue I think it'd be pretty doable: just add an if clause and 'raise Exception' right before line 91 mentioned above, then throw a test in to assert things work as expected. I'm happy to offer feedback on a PR as well. Otherwise, I'll sort this out once I'm back in front of a laptop in mid-September.

Hope that helps!

**Comment by zpencerguy** [comment]
Hi Zach,

Thanks for the taking a look at this and the well thought out reply. I totally agree with you on the point that option 3 would be the best remedy to the situation currently. Having a clear message identifying the cell with the error would quickly allow someone to troubleshoot on the spreadsheet side. I will take a look at the code to see if this is something I could help add and will create a PR if so.

Thanks!
